#######################################################################
  # training parameters
#######################################################################
train:
  max_epochs: 1000
  learning_rate: 0.0005
  batch_size: 8
#######################################################################
  # postproc parameters
#######################################################################
post:
  temperature_scaling:
    use: False
